/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as RoomsNewRouteImport } from './routes/rooms/new'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as RoomsRoomIdLobbyRouteImport } from './routes/rooms/$roomId/lobby'
import { Route as RoomsRoomIdImagesRouteImport } from './routes/rooms/$roomId/images'
import { Route as RoomsRoomIdHistoryRouteImport } from './routes/rooms/$roomId/history'
import { Route as RoomsRoomIdMatchesMatchIdRouteImport } from './routes/rooms/$roomId/matches/$matchId'
import { Route as RoomsRoomIdMatchesMatchIdSummaryRouteImport } from './routes/rooms/$roomId/matches/$matchId/summary'
import { Route as RoomsRoomIdMatchesMatchIdReplayRouteImport } from './routes/rooms/$roomId/matches/$matchId/replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsNewRoute = RoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdLobbyRoute = RoomsRoomIdLobbyRouteImport.update({
  id: '/rooms/$roomId/lobby',
  path: '/rooms/$roomId/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdImagesRoute = RoomsRoomIdImagesRouteImport.update({
  id: '/rooms/$roomId/images',
  path: '/rooms/$roomId/images',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdHistoryRoute = RoomsRoomIdHistoryRouteImport.update({
  id: '/rooms/$roomId/history',
  path: '/rooms/$roomId/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdMatchesMatchIdRoute =
  RoomsRoomIdMatchesMatchIdRouteImport.update({
    id: '/rooms/$roomId/matches/$matchId',
    path: '/rooms/$roomId/matches/$matchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoomsRoomIdMatchesMatchIdSummaryRoute =
  RoomsRoomIdMatchesMatchIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => RoomsRoomIdMatchesMatchIdRoute,
  } as any)
const RoomsRoomIdMatchesMatchIdReplayRoute =
  RoomsRoomIdMatchesMatchIdReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => RoomsRoomIdMatchesMatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/rooms/new': typeof RoomsNewRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$roomId/history': typeof RoomsRoomIdHistoryRoute
  '/rooms/$roomId/images': typeof RoomsRoomIdImagesRoute
  '/rooms/$roomId/lobby': typeof RoomsRoomIdLobbyRoute
  '/rooms/$roomId/matches/$matchId': typeof RoomsRoomIdMatchesMatchIdRouteWithChildren
  '/rooms/$roomId/matches/$matchId/replay': typeof RoomsRoomIdMatchesMatchIdReplayRoute
  '/rooms/$roomId/matches/$matchId/summary': typeof RoomsRoomIdMatchesMatchIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/rooms/new': typeof RoomsNewRoute
  '/rooms': typeof RoomsIndexRoute
  '/rooms/$roomId/history': typeof RoomsRoomIdHistoryRoute
  '/rooms/$roomId/images': typeof RoomsRoomIdImagesRoute
  '/rooms/$roomId/lobby': typeof RoomsRoomIdLobbyRoute
  '/rooms/$roomId/matches/$matchId': typeof RoomsRoomIdMatchesMatchIdRouteWithChildren
  '/rooms/$roomId/matches/$matchId/replay': typeof RoomsRoomIdMatchesMatchIdReplayRoute
  '/rooms/$roomId/matches/$matchId/summary': typeof RoomsRoomIdMatchesMatchIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/rooms/new': typeof RoomsNewRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$roomId/history': typeof RoomsRoomIdHistoryRoute
  '/rooms/$roomId/images': typeof RoomsRoomIdImagesRoute
  '/rooms/$roomId/lobby': typeof RoomsRoomIdLobbyRoute
  '/rooms/$roomId/matches/$matchId': typeof RoomsRoomIdMatchesMatchIdRouteWithChildren
  '/rooms/$roomId/matches/$matchId/replay': typeof RoomsRoomIdMatchesMatchIdReplayRoute
  '/rooms/$roomId/matches/$matchId/summary': typeof RoomsRoomIdMatchesMatchIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/join/$code'
    | '/rooms/new'
    | '/rooms/'
    | '/rooms/$roomId/history'
    | '/rooms/$roomId/images'
    | '/rooms/$roomId/lobby'
    | '/rooms/$roomId/matches/$matchId'
    | '/rooms/$roomId/matches/$matchId/replay'
    | '/rooms/$roomId/matches/$matchId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/join/$code'
    | '/rooms/new'
    | '/rooms'
    | '/rooms/$roomId/history'
    | '/rooms/$roomId/images'
    | '/rooms/$roomId/lobby'
    | '/rooms/$roomId/matches/$matchId'
    | '/rooms/$roomId/matches/$matchId/replay'
    | '/rooms/$roomId/matches/$matchId/summary'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/join/$code'
    | '/rooms/new'
    | '/rooms/'
    | '/rooms/$roomId/history'
    | '/rooms/$roomId/images'
    | '/rooms/$roomId/lobby'
    | '/rooms/$roomId/matches/$matchId'
    | '/rooms/$roomId/matches/$matchId/replay'
    | '/rooms/$roomId/matches/$matchId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinCodeRoute: typeof JoinCodeRoute
  RoomsNewRoute: typeof RoomsNewRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  RoomsRoomIdHistoryRoute: typeof RoomsRoomIdHistoryRoute
  RoomsRoomIdImagesRoute: typeof RoomsRoomIdImagesRoute
  RoomsRoomIdLobbyRoute: typeof RoomsRoomIdLobbyRoute
  RoomsRoomIdMatchesMatchIdRoute: typeof RoomsRoomIdMatchesMatchIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/new': {
      id: '/rooms/new'
      path: '/rooms/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof RoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/lobby': {
      id: '/rooms/$roomId/lobby'
      path: '/rooms/$roomId/lobby'
      fullPath: '/rooms/$roomId/lobby'
      preLoaderRoute: typeof RoomsRoomIdLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/images': {
      id: '/rooms/$roomId/images'
      path: '/rooms/$roomId/images'
      fullPath: '/rooms/$roomId/images'
      preLoaderRoute: typeof RoomsRoomIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/history': {
      id: '/rooms/$roomId/history'
      path: '/rooms/$roomId/history'
      fullPath: '/rooms/$roomId/history'
      preLoaderRoute: typeof RoomsRoomIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/matches/$matchId': {
      id: '/rooms/$roomId/matches/$matchId'
      path: '/rooms/$roomId/matches/$matchId'
      fullPath: '/rooms/$roomId/matches/$matchId'
      preLoaderRoute: typeof RoomsRoomIdMatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/matches/$matchId/summary': {
      id: '/rooms/$roomId/matches/$matchId/summary'
      path: '/summary'
      fullPath: '/rooms/$roomId/matches/$matchId/summary'
      preLoaderRoute: typeof RoomsRoomIdMatchesMatchIdSummaryRouteImport
      parentRoute: typeof RoomsRoomIdMatchesMatchIdRoute
    }
    '/rooms/$roomId/matches/$matchId/replay': {
      id: '/rooms/$roomId/matches/$matchId/replay'
      path: '/replay'
      fullPath: '/rooms/$roomId/matches/$matchId/replay'
      preLoaderRoute: typeof RoomsRoomIdMatchesMatchIdReplayRouteImport
      parentRoute: typeof RoomsRoomIdMatchesMatchIdRoute
    }
  }
}

interface RoomsRoomIdMatchesMatchIdRouteChildren {
  RoomsRoomIdMatchesMatchIdReplayRoute: typeof RoomsRoomIdMatchesMatchIdReplayRoute
  RoomsRoomIdMatchesMatchIdSummaryRoute: typeof RoomsRoomIdMatchesMatchIdSummaryRoute
}

const RoomsRoomIdMatchesMatchIdRouteChildren: RoomsRoomIdMatchesMatchIdRouteChildren =
  {
    RoomsRoomIdMatchesMatchIdReplayRoute: RoomsRoomIdMatchesMatchIdReplayRoute,
    RoomsRoomIdMatchesMatchIdSummaryRoute:
      RoomsRoomIdMatchesMatchIdSummaryRoute,
  }

const RoomsRoomIdMatchesMatchIdRouteWithChildren =
  RoomsRoomIdMatchesMatchIdRoute._addFileChildren(
    RoomsRoomIdMatchesMatchIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinCodeRoute: JoinCodeRoute,
  RoomsNewRoute: RoomsNewRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  RoomsRoomIdHistoryRoute: RoomsRoomIdHistoryRoute,
  RoomsRoomIdImagesRoute: RoomsRoomIdImagesRoute,
  RoomsRoomIdLobbyRoute: RoomsRoomIdLobbyRoute,
  RoomsRoomIdMatchesMatchIdRoute: RoomsRoomIdMatchesMatchIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
